# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Research Papers
    url: publication/
    weight: 11
  - name: News
    url: news/
    weight: 12
  - name: Projects
    url: project/
    weight: 13
  - name: Academic Services
    url: academic_services/
    weight: 14
  - name: Data Sharing
    url: data_sharing/
    weight: 15
  - name: Teaching
    url: teaching/
    weight: 16
  - name: Blog
    url: blog/
    weight: 17
